feat(3146): Allow to pass scmRepo argument to scm plugins methods [1]
screwdriver-cd/data-schema pull request #570
Opened 2024-07-17 00:23 UTC by y-oksaku

## Context

I would like to skip GitHub access if `scmRepo` is available. But some methods in the scm plugin do not allow to pass `scmRepo` argument.

https://github.com/screwdriver-cd/screwdriver/issues/3146

## Objective

Allow to pass `scmRepo` argument into methods that using `lookupScmUri` method inside.

## References

https://github.com/screwdriver-cd/screwdriver/issues/3146

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2024-07-17 04:21 UTC, yakanechi approved these changes

2024-07-17 08:32 UTC, yk634 approved these changes

2024-07-18 04:14 UTC, tkyi requested changes
I think you need to add `scmRepo` to `ADD_PR_COMMENT` as well. Otherwise, lgtm

2024-07-18 04:44 UTC, y-oksaku commented
Thank you. I added.

2024-07-18 04:48 UTC, tkyi approved these changes

2024-07-18 04:48 UTC, merged